Revert "Test image size check with intentional failure"
This reverts commit db371fb57d11ec7738fed461672cf9e23c5f8b6a.

It worked!:

```
src/_posts/2026-08-23-easy-memoization-in-crystal-with-the-memoization-shard.md: image is 760x362; expected 1200x630
Error: Process completed with exit code 1.
```